name: AVR Assembler

on: [push]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install AVRA
        run: sudo apt install avra

      - name: Build
        run: avra main.asm
        working-directory: ./Source

      - name: Prepare build artefact
        run: mv ./Source/main.hex ./micro-210-project.hex

      - uses: actions/upload-artifact@v2
        with:
          name: Build artefact
          path: ./micro-210-project.hex
